//! ESP32 XVC Server - Bare Metal Implementation with Wi-Fi
//!
//! =============================================================================
//!  CRITICAL DESIGN REQUIREMENT — DO NOT REMOVE LARGE-SHIFT STREAMING
//! =============================================================================
//!
//! Vivado does NOT reliably respect the maximum shift size advertised by
//! `getinfo:`. It may unconditionally send shift commands far larger than the
//! normal in-memory XVC buffer can hold.
//!
//! Therefore, the streaming shift path is NOT an optional optimization,
//! experimental feature, or removable compatibility workaround. It is a
//! mandatory part of this server's Vivado compatibility.
//!
//! DO NOT:
//!
//! - remove `stream_shift_command`;
//! - replace all shift handling with one fixed-size receive buffer;
//! - reject every shift larger than `MAX_SHIFT_BITS`;
//! - assume the `getinfo:` advertised size limits what Vivado will send;
//! - simplify away the two-pass TMS/TDI streaming design.
//!
//! Removing or disabling large-shift streaming WILL make this server unable
//! to handle the oversized shift commands generated by Vivado and may cause
//! FPGA programming or JTAG operations to fail.
//!
//! The normal fixed-buffer path exists only for smaller shifts.
//! Any shift larger than `MAX_SHIFT_BITS` MUST be transferred to a bounded
//! streaming implementation or another functionally equivalent large-shift
//! path.
//!
//! If this implementation is refactored, the replacement MUST preserve:
//!
//! 1. support for shifts larger than the normal in-memory buffer;
//! 2. bounded RAM usage;
//! 3. storage or reconstruction of TMS until the corresponding TDI arrives;
//! 4. incremental JTAG execution and TDO transmission;
//! 5. timeout, disconnect, abort, and Core0/Core1 synchronization behavior.
//!
//! In short:
//!
//!     VIVADO MAY IGNORE GETINFO.
//!     FIXED-SIZE-ONLY SHIFT HANDLING IS NOT COMPATIBLE.
//!     LARGE-SHIFT STREAMING MUST NEVER BE REMOVED.
//!
//! =============================================================================
//!
//! XVC (Xilinx Virtual Cable) server for JTAG programming via Wi-Fi.
//! Uses esp-radio + esp-rtos for networking, smoltcp for TCP/IP.
//!
//! Refactored for stability:
//! - JTAG controller on stack (no unsafe static)
//! - Intermittent network polling during long shifts (no blocking)
//! - Robust error handling (closes connection on protocol violation)
//! - Lower TCK max period for TCP stability
//! - Overflow-safe XVC length and TCK parsing
//! - Deterministic static RAW TMS storage for the advertised GETINFO size
//! - Independent Wi-Fi link checks and reconnect retry timing

#![feature(asm_experimental_arch)]
#![no_std]
#![no_main]

// =============================================================================
// CONDITIONAL LOGGING MACRO
// =============================================================================
// Enable with: cargo build --release --features xvc-log
// Disable for production builds to reduce code size and improve performance.

#[cfg(feature = "xvc-log")]
macro_rules! xvc_log {
    ($($arg:tt)*) => { esp_println::println!($($arg)*); }
}

#[cfg(not(feature = "xvc-log"))]
macro_rules! xvc_log {
    ($($arg:tt)*) => {{
        if false {
            let _ = core::format_args!($($arg)*);
        }
    }};
}

extern crate alloc;

use alloc::string::String;

use esp_hal::{
    clock::CpuClock,
    gpio::{Input, InputConfig, Level, Output, OutputConfig, Pull},
    interrupt::software::SoftwareInterruptControl,
    rom::ets_delay_us,
    system::Stack,
    time::{Duration, Instant},
    timer::timg::TimerGroup,
};
use esp_println::println;
use esp_rtos::CurrentThreadHandle;
use smoltcp::{
    iface::{Config as IfaceConfig, Interface, SocketHandle, SocketSet, SocketStorage},
    socket::tcp::{Socket as TcpSocket, SocketBuffer, State as TcpState},
    time::Instant as SmolInstant,
    wire::{EthernetAddress, IpCidr, Ipv4Address, Ipv4Cidr},
};
use static_cell::StaticCell;

// ROM function for system reset (not exposed by esp-hal 1.0)
// SAFETY: This is a well-known ESP32 ROM function that performs a soft reset.
unsafe extern "C" {
    fn software_reset();
}

// Required by esp-idf bootloader
esp_bootloader_esp_idf::esp_app_desc!();

// Wi-Fi configuration - read from .cargo/config.toml [env] section
const WIFI_SSID: &str = env!("WIFI_SSID");
const WIFI_PASSWORD: &str = env!("WIFI_PASSWORD");

// Network configuration - read from .cargo/config.toml [env] section
// Parse "192.168.0.100" format at compile time with validation.
const fn parse_ip(s: &str) -> [u8; 4] {
    let b = s.as_bytes();
    let mut out = [0u8; 4];
    let mut oct = 0usize;
    let mut val: u16 = 0;
    let mut have_digit = false;

    let mut i = 0usize;
    while i < b.len() {
        let c = b[i];
        if c == b'.' {
            if !have_digit {
                panic!("bad ip: missing digit before dot");
            }
            if oct >= 3 {
                panic!("bad ip: too many octets");
            }
            if val > 255 {
                panic!("bad ip: octet > 255");
            }
            out[oct] = val as u8;
            oct += 1;
            val = 0;
            have_digit = false;
        } else if c >= b'0' && c <= b'9' {
            have_digit = true;
            val = val * 10 + (c - b'0') as u16;
            if val > 255 {
                panic!("bad ip: octet > 255");
            }
        } else {
            panic!("bad ip: invalid character");
        }
        i += 1;
    }
    if !have_digit {
        panic!("bad ip: missing final digit");
    }
    if oct != 3 {
        panic!("bad ip: not 4 octets");
    }
    out[oct] = val as u8;
    out
}

/// Convert a bit count to the minimum byte count without overflow.
const fn bits_to_bytes(bits: usize) -> usize {
    bits / 8 + if bits % 8 == 0 { 0 } else { 1 }
}

#[cfg(not(feature = "esp32"))]
compile_error!(
    "This XVC server code uses hardcoded register addresses for ESP32 (Xtensa). Building for other chips (S3/C3/RISC-V) may cause hardware issues."
);

const STATIC_IP: [u8; 4] = parse_ip(env!("STATIC_IP"));
const GATEWAY_IP: [u8; 4] = parse_ip(env!("GATEWAY_IP"));
const SUBNET_PREFIX: u8 = 24;

// XVC server port
const XVC_PORT: u16 = 2542;

// XVC protocol limits
// MAX_SHIFT_BITS: largest shift handled by the normal in-memory command path.
// WARNING: Vivado ignores GETINFO and may send up to 65536 bits.
// ESP32 DRAM is limited, so we cap the normal path at 32Kbits.
const MAX_SHIFT_BITS: usize = 32_768;
const MAX_SHIFT_BYTES: usize = bits_to_bytes(MAX_SHIFT_BITS);

/// Absolute maximum bits for the streaming path.
/// Large shifts require RLE-friendly TMS data.
const STREAM_ABS_MAX_BITS: usize = 2_097_152;

/// Maximum TMS bytes stored in deterministic static RAW storage.
/// Requests at or below this size never depend on RLE compression or heap availability.
const RAW_FALLBACK_MAX_BYTES: usize = 24 * 1024;

// GETINFO reports the size guaranteed by the static RAW TMS buffer.
const GETINFO_MAX_BITS: usize = RAW_FALLBACK_MAX_BYTES * 8;
const GETINFO_RESPONSE: &[u8] = b"xvcServer_v1.0:196608\n";
const _: () = assert!(GETINFO_MAX_BITS == 196_608);

// Streaming chunk size
const CHUNK_BITS: usize = 2048;
const CHUNK_BYTES: usize = bits_to_bytes(CHUNK_BITS);

// XVC application buffer for receiving commands
// Needs: 10 + 2 * MAX_SHIFT_BYTES = 8202 bytes minimum.
const XVC_RX_BUFFER_SIZE: usize = 10 * 1024;

// Network buffers (smoltcp socket buffers)
const RX_BUFFER_SIZE: usize = 4096;
const TX_BUFFER_SIZE: usize = 4096;

// Heap size for esp-alloc (Wi-Fi + smoltcp + large-shift RLE metadata)
const HEAP_SIZE: usize = 96 * 1024;

// TCK timing limits
const MIN_TCK_PERIOD_US: u32 = 1;
const MAX_TCK_PERIOD_US: u32 = 1_000;

// Pending timeout (for stuck TCP sends)
const PENDING_TIMEOUT_MS: i64 = 10_000;

// Streaming timeouts
const STREAM_SEND_TIMEOUT_MS: i64 = 30_000;
const STREAM_RECV_TIMEOUT_MS: i64 = 30_000;

// Wi-Fi reconnection management
const WIFI_CHECK_INTERVAL_MS: i64 = 10_000;
const WIFI_RECONNECT_COOLDOWN_MS: i64 = 5_000;
const WIFI_MAX_RETRIES: u32 = 10;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum WifiState {
    Connected,
    Disconnected,
    Connecting {
        retry_count: u32,
        last_attempt_ms: i64,
    },
}

// =============================================================================
// Dual-Core Inter-Core Communication (Core0=Network, Core1=JTAG)
// =============================================================================

use core::sync::atomic::{AtomicBool, AtomicU32, AtomicUsize, Ordering};

const CMD_NONE: u32 = 0;
const CMD_SHIFT: u32 = 1;
const CMD_RESET: u32 = 2;

const ST_IDLE: u32 = 0;
const ST_BUSY: u32 = 1;
const ST_DONE: u32 = 2;
const ST_ERR: u32 = 3;

/// Mailbox for Core0 ↔ Core1 communication.
struct Mailbox {
    state: AtomicU32,
    cmd: AtomicU32,

    req_seq: AtomicU32,
    active_seq: AtomicU32,
    done_seq: AtomicU32,

    num_bits: AtomicU32,
    tck_period_us: AtomicU32,

    tms_ptr: AtomicUsize,
    tdi_ptr: AtomicUsize,
    tdo_ptr: AtomicUsize,

    abort: AtomicBool,
}

// SAFETY: All fields are atomic and may be shared between cores.
unsafe impl Sync for Mailbox {}

impl Mailbox {
    const fn new() -> Self {
        Self {
            state: AtomicU32::new(ST_IDLE),
            cmd: AtomicU32::new(CMD_NONE),
            req_seq: AtomicU32::new(0),
            active_seq: AtomicU32::new(0),
            done_seq: AtomicU32::new(0),
            num_bits: AtomicU32::new(0),
            tck_period_us: AtomicU32::new(MIN_TCK_PERIOD_US),
            tms_ptr: AtomicUsize::new(0),
            tdi_ptr: AtomicUsize::new(0),
            tdo_ptr: AtomicUsize::new(0),
            abort: AtomicBool::new(false),
        }
    }
}

static MBOX: Mailbox = Mailbox::new();

/// Value 0 means idle; a non-zero value is the active command sequence ID.
static JTAG_TOKEN: AtomicU32 = AtomicU32::new(0);

#[inline(always)]
fn next_seq() -> u32 {
    loop {
        let old = MBOX.req_seq.fetch_add(1, Ordering::Relaxed);
        let seq = old.wrapping_add(1);
        if seq != 0 {
            return seq;
        }
    }
}

struct TokenGuard {
    seq: u32,
}

impl TokenGuard {
    fn acquire(seq: u32) -> Option<Self> {
        debug_assert!(seq != 0, "Cannot acquire token with seq 0");
        JTAG_TOKEN
            .compare_exchange(0, seq, Ordering::AcqRel, Ordering::Acquire)
            .ok()
            .map(|_| TokenGuard { seq })
    }

    #[allow(dead_code)]
    fn seq(&self) -> u32 {
        self.seq
    }
}

impl Drop for TokenGuard {
    fn drop(&mut self) {
        JTAG_TOKEN.store(0, Ordering::Release);
    }
}

// =============================================================================
// STREAMING SHIFT ERROR TYPE
// =============================================================================

#[derive(Debug)]
enum StreamError {
    Disconnected,
    JtagFailed,
    Timeout,
    ShiftTooLarge,
    TmsRleOverflow,
    TmsUnderflow,
    OutOfMemory,
}

// =============================================================================
// TMS RLE COMPRESSION (for large 2-pass streaming shifts)
// =============================================================================

struct TmsRle {
    runs: alloc::vec::Vec<(u8, u32)>,
    run_idx: usize,
    run_left: u32,
}

impl TmsRle {
    fn new() -> Self {
        Self {
            runs: alloc::vec::Vec::new(),
            run_idx: 0,
            run_left: 0,
        }
    }

    fn clear(&mut self) {
        self.runs.clear();
        self.run_idx = 0;
        self.run_left = 0;
    }

    fn push_byte(&mut self, b: u8, max_runs: usize) -> Result<(), StreamError> {
        if let Some((last_b, last_len)) = self.runs.last_mut() {
            if *last_b == b && *last_len < u32::MAX {
                *last_len += 1;
                return Ok(());
            }
        }

        if self.runs.len() >= max_runs {
            return Err(StreamError::TmsRleOverflow);
        }

        if self.runs.try_reserve(1).is_err() {
            return Err(StreamError::OutOfMemory);
        }

        self.runs.push((b, 1));
        Ok(())
    }

    fn reset_cursor(&mut self) {
        self.run_idx = 0;
        self.run_left = 0;
    }

    fn fill(&mut self, out: &mut [u8]) -> Result<(), StreamError> {
        for o in out.iter_mut() {
            if self.run_left == 0 {
                if self.run_idx >= self.runs.len() {
                    return Err(StreamError::TmsUnderflow);
                }
                let (_, len) = self.runs[self.run_idx];
                self.run_left = len;
            }

            let (b, _) = self.runs[self.run_idx];
            *o = b;
            self.run_left -= 1;

            if self.run_left == 0 {
                self.run_idx += 1;
            }
        }
        Ok(())
    }
}

// =============================================================================
// STREAMING SHIFT BUFFERS / CONTEXT
// =============================================================================

use core::cell::UnsafeCell;

/// Buffers shared between Core0 and Core1 during JTAG operations.
struct JtagBuffers {
    tms_buf: UnsafeCell<[u8; CHUNK_BYTES]>,
    tdi_buf: UnsafeCell<[u8; CHUNK_BYTES]>,
    tdo_bufs: [UnsafeCell<[u8; CHUNK_BYTES]>; 2],

    /// Deterministic storage for all TMS bytes up to GETINFO_MAX_BITS.
    raw_tms_buf: UnsafeCell<[u8; RAW_FALLBACK_MAX_BYTES]>,
}

// SAFETY: Access is synchronized by JTAG_TOKEN and MBOX.done_seq.
unsafe impl Sync for JtagBuffers {}

impl JtagBuffers {
    const fn new() -> Self {
        Self {
            tms_buf: UnsafeCell::new([0u8; CHUNK_BYTES]),
            tdi_buf: UnsafeCell::new([0u8; CHUNK_BYTES]),
            tdo_bufs: [
                UnsafeCell::new([0u8; CHUNK_BYTES]),
                UnsafeCell::new([0u8; CHUNK_BYTES]),
            ],
            raw_tms_buf: UnsafeCell::new([0u8; RAW_FALLBACK_MAX_BYTES]),
        }
    }

    fn tms_ptr(&self) -> *mut u8 {
        self.tms_buf.get() as *mut u8
    }

    fn tdi_ptr(&self) -> *mut u8 {
        self.tdi_buf.get() as *mut u8
    }

    fn tdo_ptr(&self, slot: usize) -> *mut u8 {
        self.tdo_bufs[slot].get() as *mut u8
    }

    unsafe fn tms_slice_mut(&self) -> &mut [u8; CHUNK_BYTES] {
        unsafe { &mut *self.tms_buf.get() }
    }

    unsafe fn tdi_slice_mut(&self) -> &mut [u8; CHUNK_BYTES] {
        unsafe { &mut *self.tdi_buf.get() }
    }

    unsafe fn tdo_slice(&self, slot: usize) -> &[u8; CHUNK_BYTES] {
        unsafe { &*self.tdo_bufs[slot].get() }
    }

    unsafe fn raw_tms_slice_mut(&self) -> &mut [u8; RAW_FALLBACK_MAX_BYTES] {
        unsafe { &mut *self.raw_tms_buf.get() }
    }

    unsafe fn raw_tms_slice(&self) -> &[u8; RAW_FALLBACK_MAX_BYTES] {
        unsafe { &*self.raw_tms_buf.get() }
    }

    unsafe fn mask_tdo_last_byte(&self, slot: usize, chunk_bytes: usize, chunk_bits: usize) {
        unsafe {
            if chunk_bits % 8 != 0 {
                let mask = (1u8 << (chunk_bits % 8)) - 1;
                (*self.tdo_bufs[slot].get())[chunk_bytes - 1] &= mask;
            }
        }
    }
}

static JTAG_BUFS: JtagBuffers = JtagBuffers::new();

/// Reusable metadata for streaming shifts.
///
/// - Shifts up to GETINFO_MAX_BITS use static RAW TMS storage.
/// - Larger shifts use bounded RLE storage and fail safely if TMS is too complex.
/// - TDO uses two ping-pong buffers.
struct StreamContext {
    tms_rle: TmsRle,
    use_raw: bool,
    raw_len: usize,
    raw_pos: usize,

    tdo_lens: [usize; 2],
    tdo_sent: [usize; 2],
    tdo_fill_slot: usize,
    tdo_pending: usize,
}

impl StreamContext {
    fn new() -> Self {
        let mut ctx = Self {
            tms_rle: TmsRle::new(),
            use_raw: false,
            raw_len: 0,
            raw_pos: 0,
            tdo_lens: [0; 2],
            tdo_sent: [0; 2],
            tdo_fill_slot: 0,
            tdo_pending: 0,
        };

        let _ = ctx.tms_rle.runs.try_reserve(64);
        ctx
    }

    fn reset(&mut self) {
        self.tms_rle.clear();
        self.use_raw = false;
        self.raw_len = 0;
        self.raw_pos = 0;
        self.tdo_lens = [0; 2];
        self.tdo_sent = [0; 2];
        self.tdo_fill_slot = 0;
        self.tdo_pending = 0;
    }

    fn current_tdo_slot(&self) -> usize {
        self.tdo_fill_slot
    }

    fn enqueue_tdo(&mut self, len: usize) {
        self.tdo_lens[self.tdo_fill_slot] = len;
        self.tdo_sent[self.tdo_fill_slot] = 0;
        self.tdo_pending += 1;
        self.tdo_fill_slot = 1 - self.tdo_fill_slot;
    }

    fn oldest_pending_slot(&self) -> Option<usize> {
        if self.tdo_pending == 0 {
            None
        } else if self.tdo_pending == 1 {
            Some(1 - self.tdo_fill_slot)
        } else {
            Some(self.tdo_fill_slot)
        }
    }

    fn prepare_for_read(&mut self) {
        if self.use_raw {
            self.raw_pos = 0;
        } else {
            self.tms_rle.reset_cursor();
        }
    }

    fn fill_tms_into_buf(&mut self, len: usize) -> Result<(), StreamError> {
        debug_assert!(len <= CHUNK_BYTES);

        if self.use_raw {
            let end = self
                .raw_pos
                .checked_add(len)
                .ok_or(StreamError::TmsUnderflow)?;
            if end > self.raw_len {
                return Err(StreamError::TmsUnderflow);
            }

            unsafe {
                let src = &JTAG_BUFS.raw_tms_slice()[self.raw_pos..end];
                JTAG_BUFS.tms_slice_mut()[..len].copy_from_slice(src);
            }
            self.raw_pos = end;
            Ok(())
        } else {
            let buf_slice = unsafe { &mut JTAG_BUFS.tms_slice_mut()[..len] };
            self.tms_rle.fill(buf_slice)
        }
    }
}

use smoltcp::phy::Device;

/// Receive exactly `buf.len()` bytes while polling the network.
fn recv_exact<D: Device>(
    tcp_handle: SocketHandle,
    buf: &mut [u8],
    iface: &mut Interface,
    device: &mut D,
    sockets: &mut SocketSet,
) -> Result<(), StreamError> {
    let mut received = 0usize;
    let mut last_progress_ms = get_time_ms();

    while received < buf.len() {
        let ts = SmolInstant::from_millis(get_time_ms());
        iface.poll(ts, device, sockets);

        let socket = sockets.get_mut::<TcpSocket>(tcp_handle);

        if !socket.may_recv() {
            return Err(StreamError::Disconnected);
        }

        if !socket.can_recv() {
            if get_time_ms().saturating_sub(last_progress_ms) > STREAM_RECV_TIMEOUT_MS {
                return Err(StreamError::Timeout);
            }
            rtos_yield();
            continue;
        }

        match socket.recv_slice(&mut buf[received..]) {
            Ok(0) => {
                if !socket.may_recv() {
                    return Err(StreamError::Disconnected);
                }
                if get_time_ms().saturating_sub(last_progress_ms) > STREAM_RECV_TIMEOUT_MS {
                    return Err(StreamError::Timeout);
                }
                rtos_yield();
            }
            Ok(n) => {
                received += n;
                last_progress_ms = get_time_ms();
            }
            Err(smoltcp::socket::tcp::RecvError::InvalidState) => {
                return Err(StreamError::Disconnected);
            }
            Err(smoltcp::socket::tcp::RecvError::Finished) => {
                return Err(StreamError::Disconnected);
            }
            #[allow(unreachable_patterns)]
            Err(_) => {
                rtos_yield();
            }
        }
    }

    Ok(())
}

/// Read exact bytes, first consuming buffered XVC bytes and then the socket.
fn read_exact_mix<D: Device>(
    tcp_handle: SocketHandle,
    dst: &mut [u8],
    xvc_rx: &mut [u8],
    rx_head: &mut usize,
    rx_len: &mut usize,
    iface: &mut Interface,
    device: &mut D,
    sockets: &mut SocketSet,
) -> Result<(), StreamError> {
    let mut off = 0usize;

    while off < dst.len() && *rx_len > 0 {
        let take = core::cmp::min(dst.len() - off, *rx_len);
        dst[off..off + take].copy_from_slice(&xvc_rx[*rx_head..*rx_head + take]);
        *rx_head += take;
        *rx_len -= take;
        off += take;

        if *rx_len == 0 {
            *rx_head = 0;
        }
    }

    if off < dst.len() {
        recv_exact(tcp_handle, &mut dst[off..], iface, device, sockets)?;
    }

    Ok(())
}

/// Send all bytes while polling the network.
#[allow(dead_code)]
fn send_all<D: Device>(
    tcp_handle: SocketHandle,
    buf: &[u8],
    iface: &mut Interface,
    device: &mut D,
    sockets: &mut SocketSet,
) -> Result<(), StreamError> {
    let mut sent = 0usize;
    let mut last_progress_ms = get_time_ms();

    while sent < buf.len() {
        let ts = SmolInstant::from_millis(get_time_ms());
        iface.poll(ts, device, sockets);

        let socket = sockets.get_mut::<TcpSocket>(tcp_handle);

        if !socket.may_send() {
            return Err(StreamError::Disconnected);
        }

        if !socket.can_send() {
            if get_time_ms().saturating_sub(last_progress_ms) > STREAM_SEND_TIMEOUT_MS {
                return Err(StreamError::Timeout);
            }
            rtos_yield();
            continue;
        }

        match socket.send_slice(&buf[sent..]) {
            Ok(0) => {
                if !socket.may_send() {
                    return Err(StreamError::Disconnected);
                }
                if get_time_ms().saturating_sub(last_progress_ms) > STREAM_SEND_TIMEOUT_MS {
                    return Err(StreamError::Timeout);
                }
                rtos_yield();
            }
            Ok(n) => {
                sent += n;
                last_progress_ms = get_time_ms();
            }
            Err(smoltcp::socket::tcp::SendError::InvalidState) => {
                return Err(StreamError::Disconnected);
            }
            #[allow(unreachable_patterns)]
            Err(_) => {
                rtos_yield();
            }
        }
    }

    Ok(())
}

enum DrainResult {
    ProgressMade,
    NoProgress,
    Disconnected,
}

fn try_drain_tdo<D: Device>(
    tcp_handle: SocketHandle,
    ctx: &mut StreamContext,
    iface: &mut Interface,
    device: &mut D,
    sockets: &mut SocketSet,
) -> DrainResult {
    let mut made_progress = false;

    while ctx.tdo_pending > 0 {
        let slot = match ctx.oldest_pending_slot() {
            Some(slot) => slot,
            None => break,
        };

        if ctx.tdo_sent[slot] >= ctx.tdo_lens[slot] {
            ctx.tdo_lens[slot] = 0;
            ctx.tdo_sent[slot] = 0;
            ctx.tdo_pending = ctx.tdo_pending.saturating_sub(1);
            continue;
        }

        let socket = sockets.get_mut::<TcpSocket>(tcp_handle);

        if !socket.may_send() {
            return DrainResult::Disconnected;
        }

        if !socket.can_send() {
            break;
        }

        let start = ctx.tdo_sent[slot];
        let end = ctx.tdo_lens[slot];
        debug_assert!(
            start <= end,
            "TDO sent > len: slot={} sent={} len={}",
            slot,
            start,
            end
        );

        let buf = unsafe { JTAG_BUFS.tdo_slice(slot) };
        match socket.send_slice(&buf[start..end]) {
            Ok(n) if n > 0 => {
                made_progress = true;
                ctx.tdo_sent[slot] += n;

                if ctx.tdo_sent[slot] >= ctx.tdo_lens[slot] {
                    ctx.tdo_pending -= 1;
                }
            }
            Ok(_) => break,
            Err(smoltcp::socket::tcp::SendError::InvalidState) => {
                return DrainResult::Disconnected;
            }
            #[allow(unreachable_patterns)]
            Err(_) => break,
        }

        let ts = SmolInstant::from_millis(get_time_ms());
        iface.poll(ts, device, sockets);
    }

    if made_progress {
        DrainResult::ProgressMade
    } else {
        DrainResult::NoProgress
    }
}

fn flush_tdo<D: Device>(
    tcp_handle: SocketHandle,
    ctx: &mut StreamContext,
    iface: &mut Interface,
    device: &mut D,
    sockets: &mut SocketSet,
) -> Result<(), StreamError> {
    let mut last_progress_ms = get_time_ms();

    while ctx.tdo_pending > 0 {
        let ts = SmolInstant::from_millis(get_time_ms());
        iface.poll(ts, device, sockets);

        match try_drain_tdo(tcp_handle, ctx, iface, device, sockets) {
            DrainResult::Disconnected => return Err(StreamError::Disconnected),
            DrainResult::ProgressMade => last_progress_ms = get_time_ms(),
            DrainResult::NoProgress => {}
        }

        if ctx.tdo_pending > 0 {
            if get_time_ms().saturating_sub(last_progress_ms) > STREAM_SEND_TIMEOUT_MS {
                println!(
                    "Stream: TDO flush timeout (pending={}, fill_slot={})",
                    ctx.tdo_pending, ctx.tdo_fill_slot
                );
                return Err(StreamError::Timeout);
            }
            rtos_yield();
        }
    }

    Ok(())
}

/// CRITICAL: MANDATORY VIVADO COMPATIBILITY PATH — DO NOT REMOVE.
///
/// Vivado may ignore the shift-size value advertised by `getinfo:` and send a
/// shift that cannot fit in the normal fixed-size receive buffer.
///
/// This function is not an optional optimization. Do not remove it, disable it,
/// or replace it with fixed-size-only shift handling unless an equivalent
/// bounded-memory large-shift implementation is provided.
///
/// Any replacement must preserve large-shift support, TMS retention or
/// reconstruction until TDI arrives, incremental JTAG execution, TDO delivery,
/// timeout handling, disconnect aborts, and Core0/Core1 synchronization.
///
/// Process a large shift command via two-pass streaming.
///
/// XVC sends all TMS bytes before all TDI bytes, so Phase A stores/compresses TMS
/// and Phase B receives TDI chunks, performs JTAG, and streams TDO back.
fn stream_shift_command<D: Device>(
    num_bits: usize,
    jtag: &mut JtagController,
    sockets: &mut SocketSet,
    tcp_handle: SocketHandle,
    iface: &mut Interface,
    device: &mut D,
    xvc_rx: &mut [u8],
    rx_head: &mut usize,
    rx_len: &mut usize,
    ctx: &mut StreamContext,
) -> Result<(), StreamError> {
    // Validate before any rounding arithmetic. num_bits originates from the network.
    if num_bits > STREAM_ABS_MAX_BITS {
        println!(
            "Shift too large: {} bits (max {})",
            num_bits, STREAM_ABS_MAX_BITS
        );
        return Err(StreamError::ShiftTooLarge);
    }

    let num_bytes = bits_to_bytes(num_bits);

    xvc_log!("Stream start: {} bits ({} bytes)", num_bits, num_bytes);
    let stream_start_ms = get_time_ms();

    ctx.reset();

    // Requests up to the advertised GETINFO size use deterministic static RAW storage.
    // Larger requests must be RLE-friendly and are bounded to 1024 runs.
    ctx.use_raw = num_bytes <= RAW_FALLBACK_MAX_BYTES;
    let max_runs = 1024usize;

    let mut tmp = [0u8; CHUNK_BYTES];
    let mut tms_tail = [0u8; 4];
    let mut tms_seen = 0usize;
    let mut tms_remain = num_bytes;

    while tms_remain > 0 {
        let n = tms_remain.min(tmp.len());
        read_exact_mix(
            tcp_handle,
            &mut tmp[..n],
            xvc_rx,
            rx_head,
            rx_len,
            iface,
            device,
            sockets,
        )?;

        // Keep the real final four bytes regardless of chunk boundaries.
        for &b in &tmp[..n] {
            if tms_seen < tms_tail.len() {
                tms_tail[tms_seen] = b;
            } else {
                tms_tail.rotate_left(1);
                tms_tail[3] = b;
            }
            tms_seen += 1;
        }

        if ctx.use_raw {
            let end = ctx
                .raw_len
                .checked_add(n)
                .ok_or(StreamError::ShiftTooLarge)?;
            if end > RAW_FALLBACK_MAX_BYTES {
                return Err(StreamError::ShiftTooLarge);
            }

            unsafe {
                JTAG_BUFS.raw_tms_slice_mut()[ctx.raw_len..end].copy_from_slice(&tmp[..n]);
            }
            ctx.raw_len = end;
        } else {
            for &b in &tmp[..n] {
                ctx.tms_rle.push_byte(b, max_runs)?;
            }
        }

        tms_remain -= n;
    }

    ctx.prepare_for_read();

    let tail_len = num_bytes.min(tms_tail.len());
    if ctx.use_raw {
        xvc_log!(
            "Stream: {} bits, static RAW mode ({} bytes), TMS tail={:02x?}",
            num_bits,
            ctx.raw_len,
            &tms_tail[..tail_len]
        );
    } else {
        xvc_log!(
            "Stream: {} bits, {} RLE runs, TMS tail={:02x?}",
            num_bits,
            ctx.tms_rle.runs.len(),
            &tms_tail[..tail_len]
        );
    }

    let mut bits_remaining = num_bits;
    let mut total_processed = 0usize;
    let mut last_send_progress_ms = get_time_ms();

    while bits_remaining > 0 {
        let chunk_bits = core::cmp::min(bits_remaining, CHUNK_BITS);
        let chunk_bytes = bits_to_bytes(chunk_bits);

        while ctx.tdo_pending >= 2 {
            let ts = SmolInstant::from_millis(get_time_ms());
            iface.poll(ts, device, sockets);

            match try_drain_tdo(tcp_handle, ctx, iface, device, sockets) {
                DrainResult::Disconnected => return Err(StreamError::Disconnected),
                DrainResult::ProgressMade => last_send_progress_ms = get_time_ms(),
                DrainResult::NoProgress => {}
            }

            if ctx.tdo_pending >= 2 {
                if get_time_ms().saturating_sub(last_send_progress_ms) > STREAM_SEND_TIMEOUT_MS {
                    println!("Stream: TDO send stalled, client not reading");
                    return Err(StreamError::Timeout);
                }
                rtos_yield();
            }
        }

        match try_drain_tdo(tcp_handle, ctx, iface, device, sockets) {
            DrainResult::Disconnected => return Err(StreamError::Disconnected),
            DrainResult::ProgressMade => last_send_progress_ms = get_time_ms(),
            DrainResult::NoProgress => {}
        }

        ctx.fill_tms_into_buf(chunk_bytes)?;

        {
            let tdi_buf = unsafe { JTAG_BUFS.tdi_slice_mut() };
            read_exact_mix(
                tcp_handle,
                &mut tdi_buf[..chunk_bytes],
                xvc_rx,
                rx_head,
                rx_len,
                iface,
                device,
                sockets,
            )?;
        }

        let tdo_slot = ctx.current_tdo_slot();
        let tms_ptr = JTAG_BUFS.tms_ptr() as usize;
        let tdi_ptr = JTAG_BUFS.tdi_ptr() as usize;
        let tdo_ptr = JTAG_BUFS.tdo_ptr(tdo_slot) as usize;

        {
            let seq = next_seq();
            let _token = TokenGuard::acquire(seq).ok_or(StreamError::JtagFailed)?;

            MBOX.state.store(ST_IDLE, Ordering::Relaxed);
            MBOX.abort.store(false, Ordering::Relaxed);
            MBOX.tck_period_us
                .store(jtag.tck_period_us, Ordering::Relaxed);
            MBOX.num_bits.store(chunk_bits as u32, Ordering::Relaxed);
            MBOX.tms_ptr.store(tms_ptr, Ordering::Relaxed);
            MBOX.tdi_ptr.store(tdi_ptr, Ordering::Relaxed);
            MBOX.tdo_ptr.store(tdo_ptr, Ordering::Relaxed);
            MBOX.active_seq.store(seq, Ordering::Relaxed);

            if MBOX
                .cmd
                .compare_exchange(CMD_NONE, CMD_SHIFT, Ordering::Release, Ordering::Relaxed)
                .is_err()
            {
                println!("FATAL: cmd not consumed (stream)");
                unsafe { software_reset() };
            }

            let tck_us = jtag.tck_period_us as u64;
            let expected_ms = (chunk_bits as u64)
                .saturating_mul(tck_us)
                .saturating_add(999)
                / 1000;
            let deadline = Instant::now()
                + Duration::from_millis(expected_ms.saturating_mul(3).saturating_add(200));
            let hard_deadline = deadline + Duration::from_millis(2000);
            let mut soft_timeout = false;
            let mut disconnected = false;

            while MBOX.done_seq.load(Ordering::Acquire) != seq {
                let ts = SmolInstant::from_millis(get_time_ms());
                iface.poll(ts, device, sockets);

                if ctx.tdo_pending > 0 {
                    if let DrainResult::Disconnected =
                        try_drain_tdo(tcp_handle, ctx, iface, device, sockets)
                    {
                        if !disconnected {
                            disconnected = true;
                            MBOX.abort.store(true, Ordering::Release);
                        }
                    }
                }

                {
                    let socket = sockets.get_mut::<TcpSocket>(tcp_handle);
                    if !socket.may_recv() && !socket.may_send() && !disconnected {
                        disconnected = true;
                        MBOX.abort.store(true, Ordering::Release);
                    }
                }

                let now = Instant::now();
                if now > deadline && !soft_timeout {
                    let active_seq = JTAG_TOKEN.load(Ordering::Relaxed);
                    let state = MBOX.state.load(Ordering::Relaxed);
                    println!(
                        "Stream: chunk timeout (seq={}, state={}, pending={})",
                        active_seq, state, ctx.tdo_pending
                    );
                    MBOX.abort.store(true, Ordering::Release);
                    soft_timeout = true;
                }

                if now > hard_deadline {
                    println!("Stream: hard timeout, resetting");
                    unsafe { software_reset() };
                }

                rtos_yield();
            }

            if disconnected {
                return Err(StreamError::Disconnected);
            }

            if MBOX.state.load(Ordering::Acquire) != ST_DONE {
                return Err(StreamError::JtagFailed);
            }
        }

        unsafe {
            JTAG_BUFS.mask_tdo_last_byte(tdo_slot, chunk_bytes, chunk_bits);
        }

        ctx.enqueue_tdo(chunk_bytes);

        bits_remaining -= chunk_bits;
        total_processed += chunk_bits;

        if total_processed % 65_536 < CHUNK_BITS {
            xvc_log!("Stream: {}/{} bits", total_processed, num_bits);
        }
    }

    flush_tdo(tcp_handle, ctx, iface, device, sockets)?;

    let elapsed_ms = get_time_ms().saturating_sub(stream_start_ms);
    let bits_per_sec = if elapsed_ms > 0 {
        (num_bits as u64).saturating_mul(1000) / elapsed_ms as u64
    } else {
        0
    };

    xvc_log!(
        "Stream complete: {} bits in {}ms ({} kbit/s, TCK={}us)",
        num_bits,
        elapsed_ms,
        bits_per_sec / 1000,
        jtag.tck_period_us
    );

    Ok(())
}

/// Core1 stack.
static mut CORE1_STACK: Stack<16384> = Stack::new();

#[repr(align(8))]
#[allow(dead_code)]
struct AlignedHeapMem([u8; HEAP_SIZE]);

#[inline]
fn rtos_delay_ms(ms: u64) {
    CurrentThreadHandle::get().delay(Duration::from_millis(ms));
}

#[inline]
fn rtos_yield() {
    CurrentThreadHandle::get().delay(Duration::ZERO);
}

#[inline]
fn delay_us_coop(mut us: u32) {
    if us >= 2000 {
        while us > 0 {
            let chunk = us.min(250);
            ets_delay_us(chunk);
            us -= chunk;
            rtos_yield();
        }
    } else if us > 0 {
        ets_delay_us(us);
    }
}

fn init_heap() {
    use core::mem::MaybeUninit;

    static HEAP: StaticCell<MaybeUninit<AlignedHeapMem>> = StaticCell::new();
    let heap = HEAP.init_with(MaybeUninit::uninit);
    let heap_ptr = heap.as_mut_ptr() as *mut u8;

    unsafe {
        esp_alloc::HEAP.add_region(esp_alloc::HeapRegion::new(
            heap_ptr,
            HEAP_SIZE,
            esp_alloc::MemoryCapability::Internal.into(),
        ));
    }
}

/// Fast GPIO direct register access for ESP32 JTAG bit-banging.
mod fast_gpio {
    use core::ptr::{read_volatile, write_volatile};
    use core::sync::atomic::{Ordering, compiler_fence};

    const GPIO_OUT_W1TS: *mut u32 = 0x3FF44008 as *mut u32;
    const GPIO_OUT_W1TC: *mut u32 = 0x3FF4400C as *mut u32;
    const GPIO1_IN: *const u32 = 0x3FF44040 as *const u32;

    pub const TCK_MASK: u32 = 1 << 18;
    pub const TDI_MASK: u32 = 1 << 19;
    pub const TMS_MASK: u32 = 1 << 23;
    pub const TDO_BIT: u32 = 34 - 32;

    #[inline(always)]
    pub unsafe fn set_pins_with_fence(set_mask: u32, clear_mask: u32) {
        unsafe {
            if clear_mask != 0 {
                write_volatile(GPIO_OUT_W1TC, clear_mask);
            }
            if set_mask != 0 {
                write_volatile(GPIO_OUT_W1TS, set_mask);
            }
            core::arch::asm!("memw", options(nostack, preserves_flags));
        }
        compiler_fence(Ordering::Release);
    }

    #[inline(always)]
    pub unsafe fn set_high(mask: u32) {
        unsafe {
            write_volatile(GPIO_OUT_W1TS, mask);
            core::arch::asm!("memw", options(nostack, preserves_flags));
        }
    }

    #[inline(always)]
    pub unsafe fn set_low(mask: u32) {
        unsafe {
            write_volatile(GPIO_OUT_W1TC, mask);
            core::arch::asm!("memw", options(nostack, preserves_flags));
        }
    }

    #[inline(always)]
    pub unsafe fn read_tdo() -> bool {
        unsafe {
            core::arch::asm!("memw", options(nostack, preserves_flags));
            (read_volatile(GPIO1_IN) & (1 << TDO_BIT)) != 0
        }
    }
}

struct JtagController {
    _tck: Output<'static>,
    _tms: Output<'static>,
    _tdi: Output<'static>,
    _tdo: Input<'static>,
    tck_period_us: u32,
}

impl JtagController {
    fn set_tck_period(&mut self, period_ns: u32) {
        let period_us = period_ns
            .saturating_add(999)
            .checked_div(1000)
            .unwrap_or(0)
            .clamp(MIN_TCK_PERIOD_US, MAX_TCK_PERIOD_US);
        self.tck_period_us = period_us;
    }

    fn get_tck_period_ns(&self) -> u32 {
        self.tck_period_us.saturating_mul(1000)
    }
}

// =============================================================================
// Core1 JTAG functions
// =============================================================================

fn tap_reset_fast(tck_period_us: u32) -> bool {
    let high_us = ((tck_period_us + 1) / 2).max(1);
    let low_us = tck_period_us / 2;

    delay_us_coop(50);

    unsafe {
        fast_gpio::set_high(fast_gpio::TMS_MASK);
        fast_gpio::set_low(fast_gpio::TDI_MASK);
    }

    for i in 0..8 {
        if MBOX.abort.load(Ordering::Relaxed) {
            return false;
        }

        unsafe { fast_gpio::set_high(fast_gpio::TCK_MASK) };
        delay_us_coop(high_us);
        unsafe { fast_gpio::set_low(fast_gpio::TCK_MASK) };
        if low_us > 0 {
            delay_us_coop(low_us);
        }

        if tck_period_us > 100 && i % 2 == 1 {
            rtos_yield();
        }
    }

    unsafe { fast_gpio::set_low(fast_gpio::TMS_MASK) };
    unsafe { fast_gpio::set_high(fast_gpio::TCK_MASK) };
    delay_us_coop(high_us);
    unsafe { fast_gpio::set_low(fast_gpio::TCK_MASK) };
    if low_us > 0 {
        delay_us_coop(low_us);
    }

    true
}

fn shift_bits_fast(
    tck_period_us: u32,
    tms_bits: &[u8],
    tdi_bits: &[u8],
    tdo_out: &mut [u8],
    num_bits: usize,
) -> bool {
    let high_us = ((tck_period_us + 1) / 2).max(1);
    let low_us = tck_period_us / 2;

    let sample_us = (high_us / 2).max(1);
    let rest_high_us = high_us.saturating_sub(sample_us);

    let bit_us_approx = high_us + low_us + 4;
    let abort_check_bits = ((1000 / bit_us_approx).clamp(1, 4096)) as usize;
    let yield_bits = ((50_000 / bit_us_approx).clamp(1, 32_768)) as usize;

    let mut abort_counter = abort_check_bits;
    let mut yield_counter = yield_bits;
    let mut wdt_counter: u8 = 0;

    let num_bytes = bits_to_bytes(num_bits);
    for byte_idx in 0..num_bytes {
        let mut tms_byte = tms_bits[byte_idx];
        let mut tdi_byte = tdi_bits[byte_idx];
        let mut tdo_byte = 0u8;

        let bits_in_byte = if byte_idx == num_bytes - 1 {
            let rem = num_bits & 7;
            if rem == 0 { 8 } else { rem }
        } else {
            8
        };

        for bit_idx in 0..bits_in_byte {
            abort_counter -= 1;
            if abort_counter == 0 {
                abort_counter = abort_check_bits;
                if MBOX.abort.load(Ordering::Acquire) {
                    return false;
                }
            }

            yield_counter -= 1;
            if yield_counter == 0 {
                yield_counter = yield_bits;
                wdt_counter = wdt_counter.wrapping_add(1);
                if wdt_counter & 0x07 == 0 {
                    rtos_delay_ms(1);
                } else {
                    rtos_yield();
                }
            }

            let tms_bit = tms_byte & 1;
            let tdi_bit = tdi_byte & 1;

            unsafe {
                let set_mask = (if tms_bit == 1 { fast_gpio::TMS_MASK } else { 0 })
                    | (if tdi_bit == 1 { fast_gpio::TDI_MASK } else { 0 });
                let clear_mask = (if tms_bit == 0 { fast_gpio::TMS_MASK } else { 0 })
                    | (if tdi_bit == 0 { fast_gpio::TDI_MASK } else { 0 });
                fast_gpio::set_pins_with_fence(set_mask, clear_mask);
            }

            unsafe { fast_gpio::set_high(fast_gpio::TCK_MASK) };

            delay_us_coop(sample_us);

            if unsafe { fast_gpio::read_tdo() } {
                tdo_byte |= 1 << bit_idx;
            }

            if rest_high_us > 0 {
                delay_us_coop(rest_high_us);
            }

            unsafe { fast_gpio::set_low(fast_gpio::TCK_MASK) };
            if low_us > 0 {
                delay_us_coop(low_us);
            }

            tms_byte >>= 1;
            tdi_byte >>= 1;
        }

        tdo_out[byte_idx] = tdo_byte;
    }

    true
}

// =============================================================================
// CORE1 MAIN LOOP
// =============================================================================

fn core1_main() -> ! {
    println!("[Core1] Ready");

    loop {
        let mut spins = 0u32;
        while MBOX.cmd.load(Ordering::Relaxed) == CMD_NONE {
            if spins < 200 {
                rtos_yield();
                spins += 1;
            } else {
                rtos_delay_ms(1);
            }
        }

        let cmd = MBOX.cmd.swap(CMD_NONE, Ordering::AcqRel);
        if cmd == CMD_NONE {
            continue;
        }

        let seq = MBOX.active_seq.load(Ordering::Acquire);
        if seq == 0 {
            println!("Core1: FATAL active_seq=0, logic error");
            MBOX.state.store(ST_ERR, Ordering::Relaxed);
            MBOX.done_seq.store(u32::MAX, Ordering::Release);
            continue;
        }

        MBOX.state.store(ST_BUSY, Ordering::Relaxed);

        match cmd {
            CMD_RESET => {
                let tck_us = MBOX.tck_period_us.load(Ordering::Acquire);
                let ok = tap_reset_fast(tck_us);
                MBOX.state
                    .store(if ok { ST_DONE } else { ST_ERR }, Ordering::Relaxed);
            }
            CMD_SHIFT => {
                let tck_us = MBOX.tck_period_us.load(Ordering::Acquire);
                let num_bits = MBOX.num_bits.load(Ordering::Acquire) as usize;
                let num_bytes = bits_to_bytes(num_bits);

                let tms_ptr = MBOX.tms_ptr.load(Ordering::Acquire) as *const u8;
                let tdi_ptr = MBOX.tdi_ptr.load(Ordering::Acquire) as *const u8;
                let tdo_ptr = MBOX.tdo_ptr.load(Ordering::Acquire) as *mut u8;

                let ok = unsafe {
                    let tms = core::slice::from_raw_parts(tms_ptr, num_bytes);
                    let tdi = core::slice::from_raw_parts(tdi_ptr, num_bytes);
                    let tdo = core::slice::from_raw_parts_mut(tdo_ptr, num_bytes);
                    shift_bits_fast(tck_us, tms, tdi, tdo, num_bits)
                };

                MBOX.state
                    .store(if ok { ST_DONE } else { ST_ERR }, Ordering::Relaxed);
            }
            _ => {
                MBOX.state.store(ST_ERR, Ordering::Relaxed);
            }
        }

        MBOX.done_seq.store(seq, Ordering::Release);
    }
}

struct PendingRef {
    ptr: *const u8,
    len: usize,
    sent: usize,
}

impl PendingRef {
    const fn new() -> Self {
        Self {
            ptr: core::ptr::null(),
            len: 0,
            sent: 0,
        }
    }

    fn set_ref(&mut self, data: &[u8]) {
        self.ptr = data.as_ptr();
        self.len = data.len();
        self.sent = 0;
    }

    fn pending(&self) -> &[u8] {
        if self.ptr.is_null() {
            &[]
        } else {
            unsafe { core::slice::from_raw_parts(self.ptr.add(self.sent), self.len - self.sent) }
        }
    }

    fn advance(&mut self, n: usize) {
        self.sent = self.sent.saturating_add(n).min(self.len);
    }

    fn is_complete(&self) -> bool {
        self.sent >= self.len
    }

    fn clear(&mut self) {
        self.ptr = core::ptr::null();
        self.len = 0;
        self.sent = 0;
    }
}

struct XvcResult {
    consumed: usize,
    response_len: usize,
    close_connection: bool,
    streaming_shift_bits: usize,
}

fn try_process_one_command<F>(
    data: &[u8],
    out_ptr: *mut u8,
    out_cap: usize,
    jtag: &mut JtagController,
    mut poll_fn: F,
) -> Option<XvcResult>
where
    F: FnMut() -> bool,
{
    if data.len() >= 6 && data.starts_with(b"shift:") {
        if data.len() < 10 {
            return None;
        }

        let num_bits = u32::from_le_bytes([data[6], data[7], data[8], data[9]]) as usize;

        if num_bits > MAX_SHIFT_BITS {
            return Some(XvcResult {
                consumed: 10,
                response_len: 0,
                close_connection: false,
                streaming_shift_bits: num_bits,
            });
        }

        let num_bytes = bits_to_bytes(num_bits);
        let payload_len = num_bytes.checked_mul(2)?;
        let total_len = 10usize.checked_add(payload_len)?;

        if data.len() < total_len {
            return None;
        }

        if num_bytes > out_cap {
            println!("Error: Response buffer overflow");
            return Some(XvcResult {
                consumed: 0,
                response_len: 0,
                close_connection: true,
                streaming_shift_bits: 0,
            });
        }

        let seq = next_seq();
        let _token = match TokenGuard::acquire(seq) {
            Some(guard) => guard,
            None => {
                println!("Error: JTAG busy re-entry");
                return Some(XvcResult {
                    consumed: 0,
                    response_len: 0,
                    close_connection: true,
                    streaming_shift_bits: 0,
                });
            }
        };

        let tms_ptr = data.as_ptr().wrapping_add(10) as usize;
        let tdi_ptr = data.as_ptr().wrapping_add(10 + num_bytes) as usize;

        MBOX.state.store(ST_IDLE, Ordering::Relaxed);
        MBOX.abort.store(false, Ordering::Relaxed);
        MBOX.tck_period_us
            .store(jtag.tck_period_us, Ordering::Relaxed);
        MBOX.num_bits.store(num_bits as u32, Ordering::Relaxed);
        MBOX.tms_ptr.store(tms_ptr, Ordering::Relaxed);
        MBOX.tdi_ptr.store(tdi_ptr, Ordering::Relaxed);
        MBOX.tdo_ptr.store(out_ptr as usize, Ordering::Relaxed);
        MBOX.active_seq.store(seq, Ordering::Relaxed);

        if MBOX
            .cmd
            .compare_exchange(CMD_NONE, CMD_SHIFT, Ordering::Release, Ordering::Relaxed)
            .is_err()
        {
            println!("FATAL: cmd not consumed (SHIFT)");
            unsafe { software_reset() };
        }

        let tck_us = jtag.tck_period_us as i64;
        let expected_ms = (num_bits as i64).saturating_mul(tck_us).saturating_add(999) / 1000;
        let deadline = get_time_ms()
            .saturating_add(expected_ms.saturating_mul(2))
            .saturating_add(200);
        let hard_deadline = deadline.saturating_add(2000);

        let mut timed_out = false;
        loop {
            if !poll_fn() {
                MBOX.abort.store(true, Ordering::Release);
            }

            if MBOX.done_seq.load(Ordering::Acquire) == seq {
                break;
            }

            let now = get_time_ms();
            if now > deadline && !timed_out {
                xvc_log!("Core1 timeout ({}bits)", num_bits);
                MBOX.abort.store(true, Ordering::Release);
                timed_out = true;
            }

            if now > hard_deadline {
                println!("CRITICAL: Core1 stuck (SHIFT)");
                unsafe { software_reset() };
            }

            rtos_yield();
        }

        let state = MBOX.state.load(Ordering::Acquire);
        if state != ST_DONE {
            println!("Shift failed (state={})", state);
            return Some(XvcResult {
                consumed: 0,
                response_len: 0,
                close_connection: true,
                streaming_shift_bits: 0,
            });
        }

        if num_bits % 8 != 0 {
            let mask = (1u8 << (num_bits % 8)) - 1;
            unsafe {
                let out = core::slice::from_raw_parts_mut(out_ptr, num_bytes);
                out[num_bytes - 1] &= mask;
            }
        }

        #[cfg(feature = "xvc-log")]
        {
            let tdo_slice = unsafe { core::slice::from_raw_parts(out_ptr, num_bytes.min(8)) };
            let tms_slice =
                unsafe { core::slice::from_raw_parts(tms_ptr as *const u8, num_bytes.min(4)) };
            let tdi_slice =
                unsafe { core::slice::from_raw_parts(tdi_ptr as *const u8, num_bytes.min(4)) };
            xvc_log!(
                "shift: {}bits TMS={:02x?} TDI={:02x?} -> TDO={:02x?}",
                num_bits,
                tms_slice,
                tdi_slice,
                tdo_slice
            );
        }

        return Some(XvcResult {
            consumed: total_len,
            response_len: num_bytes,
            close_connection: false,
            streaming_shift_bits: 0,
        });
    }

    if data.len() < 8 {
        return None;
    }

    if data.starts_with(b"getinfo:") {
        let len = GETINFO_RESPONSE.len().min(out_cap);
        unsafe {
            core::ptr::copy_nonoverlapping(GETINFO_RESPONSE.as_ptr(), out_ptr, len);
        }
        return Some(XvcResult {
            consumed: 8,
            response_len: len,
            close_connection: false,
            streaming_shift_bits: 0,
        });
    }

    if data.starts_with(b"settck:") {
        if data.len() < 11 {
            return None;
        }
        if out_cap < 4 {
            return Some(XvcResult {
                consumed: 0,
                response_len: 0,
                close_connection: true,
                streaming_shift_bits: 0,
            });
        }

        let req_period_ns = u32::from_le_bytes([data[7], data[8], data[9], data[10]]);
        jtag.set_tck_period(req_period_ns);

        let applied_ns = jtag.get_tck_period_ns().to_le_bytes();
        unsafe {
            core::ptr::copy_nonoverlapping(applied_ns.as_ptr(), out_ptr, 4);
        }

        return Some(XvcResult {
            consumed: 11,
            response_len: 4,
            close_connection: false,
            streaming_shift_bits: 0,
        });
    }

    let log_len = data.len().min(16);
    println!(
        "Protocol Error: Unknown command. First {} bytes: {:02x?} ({:?})",
        log_len,
        &data[..log_len],
        core::str::from_utf8(&data[..log_len]).unwrap_or(".")
    );

    Some(XvcResult {
        consumed: 0,
        response_len: 0,
        close_connection: true,
        streaming_shift_bits: 0,
    })
}

// Timer for smoltcp. Only Core0 accesses START_TIME after initialization.
static mut START_TIME: Option<Instant> = None;

fn get_time_ms() -> i64 {
    unsafe {
        match START_TIME {
            Some(start) => start.elapsed().as_millis() as i64,
            None => 0,
        }
    }
}

fn init_time() {
    unsafe {
        START_TIME = Some(Instant::now());
    }
}

#[panic_handler]
fn panic(info: &core::panic::PanicInfo) -> ! {
    println!("Panic: {:?}", info);
    unsafe { software_reset() };
    loop {}
}

/// Abort an active JTAG command and wait until Core1 stops touching shared buffers.
fn abort_jtag_and_wait_done() {
    let seq = JTAG_TOKEN.load(Ordering::Acquire);
    if seq == 0 {
        return;
    }

    xvc_log!("Waiting for Core1 (seq={})...", seq);
    MBOX.abort.store(true, Ordering::Release);

    let deadline = get_time_ms().saturating_add(2000);

    while MBOX.done_seq.load(Ordering::Acquire) != seq {
        if JTAG_TOKEN.load(Ordering::Relaxed) == 0 {
            xvc_log!("abort: token dropped while waiting, exiting");
            break;
        }

        if get_time_ms() > deadline {
            println!("CRITICAL: Core1 stuck, resetting");
            unsafe { software_reset() };
        }
        rtos_yield();
    }
}

fn reset_connection(
    sockets: &mut SocketSet,
    tcp_handle: SocketHandle,
    rx_head: &mut usize,
    rx_len: &mut usize,
    pending: &mut PendingRef,
    pending_start_ms: &mut Option<i64>,
) {
    abort_jtag_and_wait_done();

    {
        let socket = sockets.get_mut::<TcpSocket>(tcp_handle);
        socket.abort();
    }

    *rx_head = 0;
    *rx_len = 0;
    pending.clear();
    *pending_start_ms = None;
    MBOX.abort.store(false, Ordering::Release);
}

#[esp_hal::main]
#[allow(unused_assignments)]
fn main() -> ! {
    let config = esp_hal::Config::default().with_cpu_clock(CpuClock::max());
    let peripherals = esp_hal::init(config);

    println!("ESP32 XVC Server v1.2 (Stable)");

    init_heap();
    init_time();

    let output_config = OutputConfig::default();
    let input_config = InputConfig::default().with_pull(Pull::None);

    let tck = Output::new(peripherals.GPIO18, Level::Low, output_config);
    let tms = Output::new(peripherals.GPIO23, Level::Low, output_config);
    let tdi = Output::new(peripherals.GPIO19, Level::Low, output_config);
    let tdo = Input::new(peripherals.GPIO34, input_config);

    let mut jtag = JtagController {
        _tck: tck,
        _tms: tms,
        _tdi: tdi,
        _tdo: tdo,
        tck_period_us: MIN_TCK_PERIOD_US,
    };

    println!("JTAG: TCK=18, TMS=23, TDI=19, TDO=34");

    // Enable GPIO34 input buffer through IO_MUX.
    const IO_MUX_GPIO34_REG: *mut u32 = 0x3FF49030 as *mut u32;
    const FUN_IE_BIT: u32 = 1 << 9;

    unsafe {
        let current = core::ptr::read_volatile(IO_MUX_GPIO34_REG);
        println!("IO_MUX_GPIO34 before = 0x{:08x}", current);
        if current & FUN_IE_BIT == 0 {
            println!("Enabling GPIO34 input (FUN_IE bit)...");
            core::ptr::write_volatile(IO_MUX_GPIO34_REG, current | FUN_IE_BIT);
        }
        let after = core::ptr::read_volatile(IO_MUX_GPIO34_REG);
        println!("IO_MUX_GPIO34 after  = 0x{:08x}", after);
    }

    println!("=== TDO Pin Diagnostic ===");

    const GPIO_IN1_REG: *const u32 = 0x3FF44040 as *const u32;
    const GPIO_ENABLE1_REG: *const u32 = 0x3FF44020 as *const u32;

    unsafe {
        let in1_val = core::ptr::read_volatile(GPIO_IN1_REG);
        let enable1_val = core::ptr::read_volatile(GPIO_ENABLE1_REG);
        println!(
            "GPIO_IN1_REG     = 0x{:08x} (bit2 = GPIO34 = {})",
            in1_val,
            if in1_val & 4 != 0 { "HIGH" } else { "LOW" }
        );
        println!("GPIO_ENABLE1_REG = 0x{:08x}", enable1_val);
    }

    let mut tdo_high_count = 0u32;
    for i in 0..10 {
        let hal_level = jtag._tdo.level();
        let reg_level = unsafe { fast_gpio::read_tdo() };
        let raw_in1 = unsafe { core::ptr::read_volatile(GPIO_IN1_REG) };
        let raw_bit2 = (raw_in1 >> 2) & 1;

        println!(
            "TDO[{}]: HAL={:?}, REG={}, RAW_IN1=0x{:08x}, bit2={}",
            i,
            hal_level,
            if reg_level { "HIGH" } else { "LOW" },
            raw_in1,
            raw_bit2
        );

        if reg_level {
            tdo_high_count += 1;
        }
        ets_delay_us(10_000);
    }

    println!("TDO: {}/10 readings were HIGH", tdo_high_count);
    if tdo_high_count == 0 {
        println!("WARNING: TDO is still LOW - check RTC_IO config!");
    } else {
        println!("SUCCESS: GPIO34 input is now working!");
    }
    println!("=========================");

    let timg0 = TimerGroup::new(peripherals.TIMG0);
    esp_rtos::start(timg0.timer0);

    let sw_int = SoftwareInterruptControl::new(peripherals.SW_INTERRUPT);
    #[allow(static_mut_refs)]
    let core1_stack = unsafe { &mut CORE1_STACK };
    esp_rtos::start_second_core(
        peripherals.CPU_CTRL,
        sw_int.software_interrupt0,
        sw_int.software_interrupt1,
        core1_stack,
        || core1_main(),
    );
    println!("[Core0] XVC Server (Atomic IPC)");

    let radio = esp_radio::init().expect("esp-radio failed");

    let wifi_config = esp_radio::wifi::Config::default();
    let (mut wifi_controller, mut interfaces) =
        esp_radio::wifi::new(&radio, peripherals.WIFI, wifi_config).expect("WiFi init failed");

    let client_config = esp_radio::wifi::ClientConfig::default()
        .with_ssid(String::from(WIFI_SSID))
        .with_password(String::from(WIFI_PASSWORD));

    wifi_controller
        .set_config(&esp_radio::wifi::ModeConfig::Client(client_config))
        .expect("WiFi config failed");

    wifi_controller.start().expect("WiFi start failed");
    println!("Connecting to {}...", WIFI_SSID);

    loop {
        match wifi_controller.connect() {
            Ok(_) => {
                println!("WiFi OK!");
                break;
            }
            Err(e) => {
                println!("Retry: {:?}", e);
                rtos_delay_ms(2000);
            }
        }
    }

    rtos_delay_ms(1000);

    let mac = esp_radio::wifi::sta_mac();
    println!(
        "MAC: {:02x}:{:02x}:{:02x}:{:02x}:{:02x}:{:02x}",
        mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]
    );

    let iface_config = IfaceConfig::new(EthernetAddress(mac).into());
    let mut iface = Interface::new(
        iface_config,
        &mut interfaces.sta,
        SmolInstant::from_millis(get_time_ms()),
    );

    iface.update_ip_addrs(|addrs| {
        addrs
            .push(IpCidr::Ipv4(Ipv4Cidr::new(
                Ipv4Address::new(STATIC_IP[0], STATIC_IP[1], STATIC_IP[2], STATIC_IP[3]),
                SUBNET_PREFIX,
            )))
            .ok();
    });

    iface
        .routes_mut()
        .add_default_ipv4_route(Ipv4Address::new(
            GATEWAY_IP[0],
            GATEWAY_IP[1],
            GATEWAY_IP[2],
            GATEWAY_IP[3],
        ))
        .ok();

    println!("========================================");
    println!("XVC Server Ready!");
    println!(
        "IP: {}.{}.{}.{}:{}",
        STATIC_IP[0], STATIC_IP[1], STATIC_IP[2], STATIC_IP[3], XVC_PORT
    );
    println!("TCK: {}us-{}us", MIN_TCK_PERIOD_US, MAX_TCK_PERIOD_US);
    println!("========================================");

    static SOCKET_STORAGE_CELL: StaticCell<[SocketStorage<'static>; 1]> = StaticCell::new();
    let socket_storage = SOCKET_STORAGE_CELL.init([SocketStorage::EMPTY; 1]);
    let mut sockets = SocketSet::new(&mut socket_storage[..]);

    static RX_BUF_CELL: StaticCell<[u8; RX_BUFFER_SIZE]> = StaticCell::new();
    static TX_BUF_CELL: StaticCell<[u8; TX_BUFFER_SIZE]> = StaticCell::new();
    let rx_buf = RX_BUF_CELL.init([0u8; RX_BUFFER_SIZE]);
    let tx_buf = TX_BUF_CELL.init([0u8; TX_BUFFER_SIZE]);

    let rx_buffer = SocketBuffer::new(&mut rx_buf[..]);
    let tx_buffer = SocketBuffer::new(&mut tx_buf[..]);
    let mut tcp_socket = TcpSocket::new(rx_buffer, tx_buffer);
    tcp_socket.listen(XVC_PORT).expect("Listen failed");
    let tcp_handle = sockets.add(tcp_socket);

    static XVC_RX_CELL: StaticCell<[u8; XVC_RX_BUFFER_SIZE]> = StaticCell::new();
    static XVC_TX_CELL: StaticCell<[u8; MAX_SHIFT_BYTES]> = StaticCell::new();
    let xvc_rx: &'static mut [u8] = XVC_RX_CELL.init([0u8; XVC_RX_BUFFER_SIZE]);
    let xvc_tx: &'static mut [u8] = XVC_TX_CELL.init([0u8; MAX_SHIFT_BYTES]);

    let mut rx_head = 0usize;
    let mut rx_len = 0usize;
    let mut prev_state = TcpState::Closed;
    let mut pending = PendingRef::new();
    let mut pending_start_ms: Option<i64> = None;

    static STREAM_CTX_CELL: StaticCell<StreamContext> = StaticCell::new();
    let stream_ctx = STREAM_CTX_CELL.init(StreamContext::new());

    let mut wifi_state = WifiState::Connected;
    let mut last_wifi_check_ms = get_time_ms();

    loop {
        let now_ms = get_time_ms();
        let timestamp = SmolInstant::from_millis(now_ms);

        // Link health is sampled periodically, but reconnect attempts are timed
        // independently below, so a 5-second cooldown is really 5 seconds.
        if now_ms.saturating_sub(last_wifi_check_ms) >= WIFI_CHECK_INTERVAL_MS {
            last_wifi_check_ms = now_ms;
            let is_connected = wifi_controller.is_connected().unwrap_or(false);

            match wifi_state {
                WifiState::Connected if !is_connected => {
                    xvc_log!("Wi-Fi disconnected, attempting recovery...");
                    wifi_state = WifiState::Disconnected;
                    reset_connection(
                        &mut sockets,
                        tcp_handle,
                        &mut rx_head,
                        &mut rx_len,
                        &mut pending,
                        &mut pending_start_ms,
                    );
                }
                WifiState::Disconnected if is_connected => {
                    wifi_state = WifiState::Connected;
                    xvc_log!("Wi-Fi link recovered externally");
                }
                WifiState::Connecting { retry_count, .. } if is_connected => {
                    wifi_state = WifiState::Connected;
                    xvc_log!("Wi-Fi connected after {} retries", retry_count);
                }
                _ => {}
            }
        }

        // Reconnect state machine runs every main-loop iteration.
        match wifi_state {
            WifiState::Connected => {}
            WifiState::Disconnected => {
                xvc_log!("Wi-Fi: reconnect attempt 1");
                match wifi_controller.connect() {
                    Ok(_) => {
                        wifi_state = WifiState::Connected;
                        xvc_log!("Wi-Fi reconnected!");
                        let ts = SmolInstant::from_millis(get_time_ms());
                        iface.poll(ts, &mut interfaces.sta, &mut sockets);
                    }
                    Err(_) => {
                        wifi_state = WifiState::Connecting {
                            retry_count: 1,
                            last_attempt_ms: now_ms,
                        };
                    }
                }
            }
            WifiState::Connecting {
                retry_count,
                last_attempt_ms,
            } => {
                if now_ms.saturating_sub(last_attempt_ms) >= WIFI_RECONNECT_COOLDOWN_MS {
                    if retry_count >= WIFI_MAX_RETRIES {
                        println!(
                            "Wi-Fi: {} retries failed, resetting device",
                            WIFI_MAX_RETRIES
                        );
                        unsafe { software_reset() };
                    }

                    let next_retry = retry_count + 1;
                    xvc_log!("Wi-Fi: reconnect attempt {}", next_retry);
                    match wifi_controller.connect() {
                        Ok(_) => {
                            wifi_state = WifiState::Connected;
                            xvc_log!("Wi-Fi reconnected!");
                            let ts = SmolInstant::from_millis(get_time_ms());
                            iface.poll(ts, &mut interfaces.sta, &mut sockets);
                        }
                        Err(_) => {
                            wifi_state = WifiState::Connecting {
                                retry_count: next_retry,
                                last_attempt_ms: now_ms,
                            };
                        }
                    }
                }
            }
        }

        iface.poll(timestamp, &mut interfaces.sta, &mut sockets);

        {
            let socket = sockets.get_mut::<TcpSocket>(tcp_handle);

            if !socket.is_open() {
                if prev_state != TcpState::Listen && prev_state != TcpState::Closed {
                    xvc_log!("Re-listening...");
                }

                rx_head = 0;
                rx_len = 0;
                pending.clear();
                pending_start_ms = None;

                if let Err(e) = socket.listen(XVC_PORT) {
                    println!("Listen error: {:?}", e);
                }
            }
        }

        let current_state = sockets.get_mut::<TcpSocket>(tcp_handle).state();
        let just_connected =
            current_state == TcpState::Established && prev_state != TcpState::Established;

        if just_connected {
            {
                let socket = sockets.get_mut::<TcpSocket>(tcp_handle);
                socket.set_nagle_enabled(false);
            }

            xvc_log!("New client, TAP reset");
            jtag.tck_period_us = MIN_TCK_PERIOD_US;

            let seq = next_seq();
            let _token = match TokenGuard::acquire(seq) {
                Some(guard) => guard,
                None => {
                    println!("FATAL: JTAG busy on RESET");
                    unsafe { software_reset() };
                    loop {}
                }
            };

            MBOX.state.store(ST_IDLE, Ordering::Relaxed);
            MBOX.abort.store(false, Ordering::Relaxed);
            MBOX.tck_period_us
                .store(jtag.tck_period_us, Ordering::Relaxed);
            MBOX.active_seq.store(seq, Ordering::Relaxed);

            if MBOX
                .cmd
                .compare_exchange(CMD_NONE, CMD_RESET, Ordering::Release, Ordering::Relaxed)
                .is_err()
            {
                println!("FATAL: cmd not consumed (RESET)");
                unsafe { software_reset() };
            }

            let reset_deadline = get_time_ms().saturating_add(2000);
            let hard_deadline = reset_deadline.saturating_add(2000);
            let mut reset_timed_out = false;

            while MBOX.done_seq.load(Ordering::Acquire) != seq {
                let ts = SmolInstant::from_millis(get_time_ms());
                iface.poll(ts, &mut interfaces.sta, &mut sockets);

                let now = get_time_ms();
                if now > reset_deadline && !reset_timed_out {
                    xvc_log!("Reset timeout, aborting");
                    MBOX.abort.store(true, Ordering::Release);
                    reset_timed_out = true;
                }

                if now > hard_deadline {
                    println!("CRITICAL: Core1 stuck (RESET)");
                    unsafe { software_reset() };
                }

                rtos_yield();
            }

            rx_head = 0;
            rx_len = 0;
            pending.clear();
            pending_start_ms = None;
            xvc_log!("New connection initialized");

            let state = MBOX.state.load(Ordering::Acquire);
            if state != ST_DONE {
                println!("Reset failed ({})", state);
                let socket = sockets.get_mut::<TcpSocket>(tcp_handle);
                socket.abort();
            }
        }

        prev_state = sockets.get_mut::<TcpSocket>(tcp_handle).state();

        {
            let socket = sockets.get_mut::<TcpSocket>(tcp_handle);

            if socket.is_open() {
                while !pending.is_complete() && socket.can_send() {
                    match socket.send_slice(pending.pending()) {
                        Ok(sent) if sent > 0 => {
                            pending.advance(sent);
                            pending_start_ms = Some(get_time_ms());
                        }
                        _ => break,
                    }
                }

                if !pending.is_complete() {
                    let now = get_time_ms();
                    if let Some(start) = pending_start_ms {
                        if now.saturating_sub(start) > PENDING_TIMEOUT_MS {
                            println!("Pending timeout, aborting connection");
                            socket.abort();
                            rx_head = 0;
                            rx_len = 0;
                            pending.clear();
                            pending_start_ms = None;
                        }
                    } else {
                        pending_start_ms = Some(now);
                    }
                } else {
                    pending_start_ms = None;
                }

                if JTAG_TOKEN.load(Ordering::Acquire) == 0
                    && pending.is_complete()
                    && socket.can_recv()
                {
                    if rx_len == 0 {
                        rx_head = 0;
                    }

                    let write_pos = rx_head + rx_len;
                    if write_pos == XVC_RX_BUFFER_SIZE {
                        if rx_head == 0 {
                            println!("Error: RX buffer overflow, aborting connection");
                            socket.abort();
                            rx_head = 0;
                            rx_len = 0;
                            pending.clear();
                            pending_start_ms = None;
                        } else {
                            xvc_rx.copy_within(rx_head..rx_head + rx_len, 0);
                            rx_head = 0;
                        }
                    }

                    let write_pos = rx_head + rx_len;
                    let space = XVC_RX_BUFFER_SIZE - write_pos;

                    if space > 0 {
                        if let Ok(n) = socket.recv(|buf| {
                            let len = buf.len().min(space);
                            xvc_rx[write_pos..write_pos + len].copy_from_slice(&buf[..len]);
                            (len, len)
                        }) {
                            if n == 0 && !socket.may_recv() {
                                xvc_log!("Connection closed by peer");
                                socket.close();
                            } else {
                                rx_len += n;
                            }
                        }
                    }
                }
            }

            prev_state = socket.state();
        }

        while rx_len > 0 && pending.is_complete() {
            let result_opt = {
                let poll_callback = || -> bool {
                    let ts = SmolInstant::from_millis(get_time_ms());
                    iface.poll(ts, &mut interfaces.sta, &mut sockets);

                    let socket = sockets.get_mut::<TcpSocket>(tcp_handle);
                    socket.may_recv() || socket.may_send()
                };

                try_process_one_command(
                    &xvc_rx[rx_head..rx_head + rx_len],
                    xvc_tx.as_mut_ptr(),
                    xvc_tx.len(),
                    &mut jtag,
                    poll_callback,
                )
            };

            match result_opt {
                Some(result) => {
                    if result.close_connection {
                        println!("Aborting connection due to protocol error");
                        reset_connection(
                            &mut sockets,
                            tcp_handle,
                            &mut rx_head,
                            &mut rx_len,
                            &mut pending,
                            &mut pending_start_ms,
                        );
                        break;
                    }

                    if result.streaming_shift_bits > 0 {
                        rx_head += result.consumed;
                        rx_len -= result.consumed;
                        if rx_len == 0 {
                            rx_head = 0;
                        }

                        let stream_result = stream_shift_command(
                            result.streaming_shift_bits,
                            &mut jtag,
                            &mut sockets,
                            tcp_handle,
                            &mut iface,
                            &mut interfaces.sta,
                            xvc_rx,
                            &mut rx_head,
                            &mut rx_len,
                            stream_ctx,
                        );

                        if let Err(error) = stream_result {
                            println!("Stream failed: {:?}", error);
                            reset_connection(
                                &mut sockets,
                                tcp_handle,
                                &mut rx_head,
                                &mut rx_len,
                                &mut pending,
                                &mut pending_start_ms,
                            );
                            break;
                        }

                        continue;
                    }

                    if result.response_len > 0 {
                        pending.set_ref(&xvc_tx[..result.response_len]);
                        pending_start_ms = Some(get_time_ms());
                    }

                    rx_head += result.consumed;
                    rx_len -= result.consumed;
                    if rx_len == 0 {
                        rx_head = 0;
                    }
                }
                None => break,
            }
        }

        let has_work =
            prev_state == TcpState::Established && (rx_len > 0 || !pending.is_complete());

        if has_work {
            rtos_yield();
        } else {
            rtos_delay_ms(1);
        }
    }
}
